### ISSUE TITLE
Install fails on PHP 7.2: implicit declaration of function 'zval_get_tmp_string'

### ISSUE THREAD

**Issue by mlocati** [php-rdkafka/php-rdkafka#566]
### Description

Accordingly to the [package.xml file](https://github.com/arnaud-lb/php-rdkafka/blob/6.0.4/package.xml#L167), the minimum required PHP version is 7.0,

But the extension fails to compile on PHP 7.2

Here's what I do in a docker container started with `docker run --rm -it php:7.2-cli-alpine3.12 sh`

```
$ apk add $PHPIZE_DEPS librdkafka-dev

$ pecl install rdkafka
[...]
/tmp/pear/temp/rdkafka/rdkafka.c:492:46: warning: implicit declaration of function 'zval_get_tmp_string'; did you mean 'zval_get_string'? [-Wimplicit-function-declaration]
  492 |             zend_string *extension_val_str = zval_get_tmp_string(extension_zval, &tmp_extension_val_str);
      |                                              ^~~~~~~~~~~~~~~~~~~
      |                                              zval_get_string
/tmp/pear/temp/rdkafka/rdkafka.c:492:46: warning: initialization of 'zend_string *' {aka 'struct _zend_string *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
[...]

$ docker-php-ext-enable rdkafka
php --ri rdkafka
PHP Warning:  PHP Startup: Unable to load dynamic library 'rdkafka' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/rdkafka (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20170718/rdkafka: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20170718/rdkafka.so (Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20170718/rdkafka.so: zval_get_tmp_string: symbol not found)) in Unknown on line 0


### php-rdkafka Version

php-rdkafka 6.0.4

### librdkafka Version

_No response_

### PHP Version

PHP 7.2

### Operating System

Alpine

### Kafka Version

_No response_

**Comment by arnaud-lb** [comment]
Closing as duplicate of https://github.com/arnaud-lb/php-rdkafka/issues/562. 

Thank you for the report!
